sudo: required
services:
  - docker
before_install:
  - docker build -t dockersrana/docker-react-app -f Dockerfile.dev .

script:
  - docker run dockersrana/docker-react-app npm run test -- --coverage
