sudo: required
services:
  - docker
before_install:
  - docker build -t dockersrana/docker-react-app -f Dockerfile.dev .

script:
  - docker run dockersrana/docker-react-app npm run test -- --coverage
deploy:
  provider: elasticbeanstack
  region: "us-west-2"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstack-us-west-2-3064476627547"
  bucket_path: "docker"
  on:
    branch: master